version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --unsafe-perm
      - npm install babel-cli cross-env webpack-cli --global
  build:
    commands:
       - npm run docs
artifacts:
  files:
    - '**/*'
  base-directory: 'docsdocs'
cache:
  paths:
    - './node_modules/**/*'
